# Generated by Django 5.2.16 on 2026-07-22 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('resume_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('activity_score', models.IntegerField(default=0)),
                ('readiness_level', models.CharField(blank=True, max_length=50)),
                ('breakdown_json', models.TextField(blank=True)),
                ('action_plan_json', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
